# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jan 22 21:36:40 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(561, 557)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.searchBox = QtGui.QGroupBox(self.centralwidget)
        self.searchBox.setObjectName(_fromUtf8("searchBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.searchBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.searchBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.artist = QtGui.QLineEdit(self.searchBox)
        self.artist.setObjectName(_fromUtf8("artist"))
        self.horizontalLayout_3.addWidget(self.artist)
        self.label_3 = QtGui.QLabel(self.searchBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.title = QtGui.QLineEdit(self.searchBox)
        self.title.setObjectName(_fromUtf8("title"))
        self.horizontalLayout_3.addWidget(self.title)
        self.search = QtGui.QPushButton(self.searchBox)
        self.search.setObjectName(_fromUtf8("search"))
        self.horizontalLayout_3.addWidget(self.search)
        self.verticalLayout_2.addWidget(self.searchBox)
        self.pathBox = QtGui.QGroupBox(self.centralwidget)
        self.pathBox.setObjectName(_fromUtf8("pathBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.pathBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.pathBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit = QtGui.QLineEdit(self.pathBox)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.toolButton = QtGui.QToolButton(self.pathBox)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_5.addWidget(self.toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.pathBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.fileSelectEdit = QtGui.QLineEdit(self.pathBox)
        self.fileSelectEdit.setObjectName(_fromUtf8("fileSelectEdit"))
        self.horizontalLayout_4.addWidget(self.fileSelectEdit)
        self.chooseFile = QtGui.QToolButton(self.pathBox)
        self.chooseFile.setObjectName(_fromUtf8("chooseFile"))
        self.horizontalLayout_4.addWidget(self.chooseFile)
        self.showTag = QtGui.QPushButton(self.pathBox)
        self.showTag.setObjectName(_fromUtf8("showTag"))
        self.horizontalLayout_4.addWidget(self.showTag)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.pathBox)
        self.optionBox = QtGui.QGroupBox(self.centralwidget)
        self.optionBox.setObjectName(_fromUtf8("optionBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.optionBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.checkVerbose = QtGui.QCheckBox(self.optionBox)
        self.checkVerbose.setObjectName(_fromUtf8("checkVerbose"))
        self.verticalLayout_5.addWidget(self.checkVerbose)
        self.checkRecursive = QtGui.QCheckBox(self.optionBox)
        self.checkRecursive.setObjectName(_fromUtf8("checkRecursive"))
        self.verticalLayout_5.addWidget(self.checkRecursive)
        self.checkOverride = QtGui.QCheckBox(self.optionBox)
        self.checkOverride.setObjectName(_fromUtf8("checkOverride"))
        self.verticalLayout_5.addWidget(self.checkOverride)
        self.checkID3 = QtGui.QCheckBox(self.optionBox)
        self.checkID3.setObjectName(_fromUtf8("checkID3"))
        self.verticalLayout_5.addWidget(self.checkID3)
        self.verticalLayout_2.addWidget(self.optionBox)
        self.buttonsBox = QtGui.QVBoxLayout()
        self.buttonsBox.setObjectName(_fromUtf8("buttonsBox"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pauseButton = QtGui.QPushButton(self.centralwidget)
        self.pauseButton.setObjectName(_fromUtf8("pauseButton"))
        self.horizontalLayout.addWidget(self.pauseButton)
        self.goButton = QtGui.QPushButton(self.centralwidget)
        self.goButton.setObjectName(_fromUtf8("goButton"))
        self.horizontalLayout.addWidget(self.goButton)
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout.addWidget(self.stopButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonsBox.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.buttonsBox)
        self.progressBox = QtGui.QHBoxLayout()
        self.progressBox.setObjectName(_fromUtf8("progressBox"))
        self.labelprogressBar = QtGui.QLabel(self.centralwidget)
        self.labelprogressBar.setObjectName(_fromUtf8("labelprogressBar"))
        self.progressBox.addWidget(self.labelprogressBar)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.progressBox.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.progressBox)
        self.listContent = QtGui.QListWidget(self.centralwidget)
        self.listContent.setObjectName(_fromUtf8("listContent"))
        self.verticalLayout_2.addWidget(self.listContent)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_File = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen_File.setIcon(icon1)
        self.actionOpen_File.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionOpen_File.setObjectName(_fromUtf8("actionOpen_File"))
        self.actionOpen_Directory = QtGui.QAction(MainWindow)
        self.actionOpen_Directory.setIcon(icon)
        self.actionOpen_Directory.setObjectName(_fromUtf8("actionOpen_Directory"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionOpen_Directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label_2.setBuddy(self.artist)
        self.label_3.setBuddy(self.title)
        self.label_4.setBuddy(self.fileSelectEdit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.artist, self.title)
        MainWindow.setTabOrder(self.title, self.search)
        MainWindow.setTabOrder(self.search, self.checkVerbose)
        MainWindow.setTabOrder(self.checkVerbose, self.checkRecursive)
        MainWindow.setTabOrder(self.checkRecursive, self.checkOverride)
        MainWindow.setTabOrder(self.checkOverride, self.checkID3)
        MainWindow.setTabOrder(self.checkID3, self.pauseButton)
        MainWindow.setTabOrder(self.pauseButton, self.goButton)
        MainWindow.setTabOrder(self.goButton, self.stopButton)
        MainWindow.setTabOrder(self.stopButton, self.listContent)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.searchBox.setTitle(QtGui.QApplication.translate("MainWindow", "Simple Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Artist:", None, QtGui.QApplication.UnicodeUTF8))
        self.artist.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Enter artist name</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.artist.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter artist name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Enter song title</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter song title", None, QtGui.QApplication.UnicodeUTF8))
        self.search.setToolTip(QtGui.QApplication.translate("MainWindow", "Launch research", None, QtGui.QApplication.UnicodeUTF8))
        self.search.setStatusTip(QtGui.QApplication.translate("MainWindow", "Launch research on ParolesMania", None, QtGui.QApplication.UnicodeUTF8))
        self.search.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Launch search</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.search.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pathBox.setTitle(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Select a directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Select a directory to lookup", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Select a directory to lookup", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Select a file:", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSelectEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>MP3 files to Tag</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSelectEdit.setStatusTip(QtGui.QApplication.translate("MainWindow", "MP3 files to Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.showTag.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Show current tags</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.showTag.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show current tags", None, QtGui.QApplication.UnicodeUTF8))
        self.showTag.setText(QtGui.QApplication.translate("MainWindow", "Show Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.optionBox.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.checkVerbose.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Print verbose output</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkVerbose.setText(QtGui.QApplication.translate("MainWindow", "Verbose", None, QtGui.QApplication.UnicodeUTF8))
        self.checkRecursive.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Search MP3 files in subdirectories</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkRecursive.setText(QtGui.QApplication.translate("MainWindow", "Do not do recursive directory search", None, QtGui.QApplication.UnicodeUTF8))
        self.checkOverride.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Replace existing lyrics if they are found on internet</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkOverride.setText(QtGui.QApplication.translate("MainWindow", "Do not override existing lyrics", None, QtGui.QApplication.UnicodeUTF8))
        self.checkID3.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Save tags in IDv3.2.4 (Windows Media Player does not support this version yet)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkID3.setText(QtGui.QApplication.translate("MainWindow", "Save in IDv3.2.4 instead of 3.2.3 (incompatible with Windows Media Player)", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Pause the tagging</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseButton.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.goButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Start Lyrics search and tag</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.goButton.setText(QtGui.QApplication.translate("MainWindow", "Go !", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Stop tagging</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.labelprogressBar.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_File.setText(QtGui.QApplication.translate("MainWindow", "Open File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_File.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_File.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Directory.setText(QtGui.QApplication.translate("MainWindow", "Open Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Directory.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Directory.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Exit LyricsTagger", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setStatusTip(QtGui.QApplication.translate("MainWindow", "About LyricsTagger", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))

import qrc_resources
